version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=car_db
      - JWT_SECRET_KEY=supersecretkey-change-this-in-production
      - INTERNAL_SERVICE_TOKEN=internal-ai-secret-token
      - CLOUDINARY_CLOUD_NAME=dp4visgbh
      - CLOUDINARY_API_KEY=973616849892656
      - CLOUDINARY_API_SECRET=35tUFXGMLloa-Eqjpjm3Z2Qj6O4
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads

  seed:
    build: .
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=car_db
      - JWT_SECRET_KEY=supersecretkey-change-this-in-production
      - INTERNAL_SERVICE_TOKEN=internal-ai-secret-token
      - CLOUDINARY_CLOUD_NAME=dp4visgbh
      - CLOUDINARY_API_KEY=973616849892656
      - CLOUDINARY_API_SECRET=35tUFXGMLloa-Eqjpjm3Z2Qj6O4
    command: python seed/seed_db.py
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  mongodb_data:
  ollama_data:
